# GCP App Engine Configuration (Alternative to Cloud Run)
# Deploy: gcloud app deploy

runtime: python311

# App Engine service (use 'default' or custom service name)
service: default

# Instance class (determines CPU/memory)
# F1 (600 MHz, 256 MB) - Free tier
# F2 (1.2 GHz, 512 MB) - Basic
# F4 (2.4 GHz, 1 GB) - Standard
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  # Minimum instances (keep 0 to reduce costs)
  min_instances: 0
  
  # Maximum instances
  max_instances: 5
  
  # Minimum pending latency before spinning up new instance
  min_pending_latency: 30ms
  
  # Maximum pending latency before spinning up new instance
  max_pending_latency: automatic
  
  # Target CPU utilization
  target_cpu_utilization: 0.65
  
  # Target throughput utilization
  target_throughput_utilization: 0.6

# Environment variables
# IMPORTANT: Use Secret Manager for sensitive data in production!
env_variables:
  PYTHONUNBUFFERED: "1"
  LOG_DIR: "/tmp/logs"

# Handlers (URL routing)
handlers:
# Static files (if any)
- url: /static
  static_dir: static
  secure: always

# Health check endpoint
- url: /health
  script: auto
  secure: always

# All other requests
- url: /.*
  script: auto
  secure: always

# Entrypoint (override default)
entrypoint: python Ai_ticket_processor.py --limit 50

# VPC Access Connector (if needed for private resources)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME

# Network settings
network:
  # Allow outbound connections
  forwarded_ports: []
  
  # Session affinity (not typically needed for batch processing)
  session_affinity: false

# Readiness check
readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Liveness check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
